### ISSUE TITLE
loading new addons folder doesn't work

### ISSUE THREAD

**Issue by Garibaldy** [iterativo-git/dockerdoo#105]
#15  
under the file ".env" update the variable like this 

 ODOO_EXTRA_ADDONS = /mnt/extra-addons/,/mnt/extra-addons/**account-financial-tools-12.0/**
 or
 ODOO_EXTRA_ADDONS = /mnt/extra-addons/,/mnt/extra-addons/**OCA/account-financial-tools-12.0/**
 

![image](https://user-images.githubusercontent.com/3017653/92313706-1047ba80-efa5-11ea-9033-cf20f915d93c.png)

**Comment by Garibaldy** [comment]
As @akevinieron  explained in #15 and @gustavovalverde  said the reason of this is because it only discover modules at one level at a time, 

**Example 1**

```
root/folder-module-A/modules
        folder-module-B/modules
        folder-module-C/modules
```

**this is okay** 
---
**Example 2**
but if i install in differents levels it only will pick the first

```
root/folder-module-A/modules
       folder-module-B/modules
       module-A
```
**This is wrong**

in this case it wil**l only pick module-A** folder and ignore folder-module-A and folder-module-B  (modules)

**Comment by Garibaldy** [comment]
@gustavovalverde  there is a way to setup an option in the config file to allow multi-level discovery , which one level is the default as right now for best practice ?

**Comment by akevinieron** [comment]
@Garibaldy Actually this isn't a feature but an issue.

**Comment by Garibaldy** [comment]
@akevinieron i'm agree, that should be the decision of who's implementing,  i'm not sure but i think all this goes to the script **getaddons.py**

**Comment by Garibaldy** [comment]
Guys did you have the opportunity to check this code?  @akevinieron @gustavovalverde 

i know it needs further modifications related of how it handle depth searching and remove duplicated code i just did KISS

**Comment by gustavovalverde** [comment]
Seeing this issue now, sorry.

Actually, it's a bad practice to have multilevel on Odoo, all modules should be at the same level. It's even a python best practice for packages, as there's a standard way for python and Odoo to build modules.

This issue commonly arises when your module has the __init__.py on the root of a repository, which is a bad practice. Even if you have a single module, it should be inside a folder with the name of the module.

Please check, if this is not your use case, or it's actually an issue on not reading when all the modules are at the same level. This is also required in the README

https://github.com/iterativo-git/dockerdoo/blob/13.0/README.md#project-structure
