### ISSUE TITLE
/entrypoint.sh: line 105: exec: : not found

### ISSUE THREAD

**Issue by netfxtech** [iterativo-git/dockerdoo#117]
I made changes to the .env file but kept receiving this error. Deleted folder/repo and started fresh with your instructions

"
git clone -b 14.0 git@github.com:iterativo-git/dockerdoo.git && cd dockerdoo
git clone --depth=1 -b 14.0 git@github.com:odoo/odoo.git src/odoo
docker-compose -f docker-compose.yml -f dev-hosted.yml **up -d** (I added up -d)

![image](https://user-images.githubusercontent.com/62037189/108665267-65ab5180-7489-11eb-8b81-6b9d670497ac.png)

**Comment by gustavovalverde** [comment]
I'm working on a big refactor to accomplish this. I'll reference this issue when solved

**Comment by dev-flti** [comment]
Hi, 

i still get this error, even after i updated the Dockerfile with your given fix.

<img width="721" alt="Bildschirmfoto 2021-04-22 um 18 07 19" src="https://user-images.githubusercontent.com/64775806/115747554-aba36980-a395-11eb-8714-6fc693380d3d.png">

I added to my Dockerfile:

<img width="1170" alt="Bildschirmfoto 2021-04-22 um 18 07 10" src="https://user-images.githubusercontent.com/64775806/115747601-b52cd180-a395-11eb-8f8c-9ae5769881d7.png">


is there any additional setting i have to change or add? 

Working with macOs BigSur!

**Comment by dev-flti** [comment]
@gustavovalverde  Any suggestion here?
