### ISSUE TITLE
Odoo crash with PermissionError after fresh container build

### ISSUE THREAD

**Issue by jlopezg** [iterativo-git/dockerdoo#127]
**Versión**:
13.0

> 2021-04-06 14:52:58,726 1 ERROR ? werkzeug: Error on request:
> odoo_1  | Traceback (most recent call last):
> odoo_1  |   File "/usr/local/lib/python3.8/site-packages/werkzeug/serving.py", line 303, in run_wsgi
> odoo_1  |     execute(self.server.app)
> odoo_1  |   File "/usr/local/lib/python3.8/site-packages/werkzeug/serving.py", line 291, in execute
> odoo_1  |     application_iter = app(environ, start_response)
> odoo_1  |   File "/opt/odoo/odoo/service/server.py", line 439, in app
> odoo_1  |     return self.app(e, s)
> odoo_1  |   File "/opt/odoo/odoo/service/wsgi_server.py", line 142, in application
> odoo_1  |     return application_unproxied(environ, start_response)
> odoo_1  |   File "/opt/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
> odoo_1  |     result = odoo.http.root(environ, start_response)
> odoo_1  |   File "/opt/odoo/odoo/http.py", line 1287, in __call__
> odoo_1  |     return self.dispatch(environ, start_response)
> odoo_1  |   File "/opt/odoo/odoo/http.py", line 1257, in __call__
> odoo_1  |     return self.app(environ, start_wrapped)
> odoo_1  |   File "/usr/local/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 252, in __call__
> odoo_1  |     start_response("200 OK", headers)
> odoo_1  |   File "/opt/odoo/odoo/http.py", line 1246, in start_wrapped
> odoo_1  |     root.setup_session(req)
> odoo_1  |   File "/opt/odoo/odoo/http.py", line 1318, in setup_session
> odoo_1  |     session_gc(self.session_store)
> odoo_1  |   File "/opt/odoo/odoo/tools/func.py", line 24, in __get__
> odoo_1  |     value = self.fget(obj)
> odoo_1  |   File "/opt/odoo/odoo/http.py", line 1268, in session_store
> odoo_1  |     path = odoo.tools.config.session_dir
> odoo_1  |   File "/opt/odoo/odoo/tools/config.py", line 681, in session_dir
> odoo_1  |     os.makedirs(d, 0o700)
> odoo_1  |   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
> odoo_1  |     mkdir(name, mode)
> odoo_1  | PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/data/sessions' - - -

**Comment by Garibaldy** [comment]
The same thing is happening to me, with a fresh dockerdoo instance but with v12.0

**Comment by Garibaldy** [comment]
> The same thing is happening to me, with a fresh dockerdoo instance but with v12.0

rebuilding the image fixed the problem, so the solution is to update the image in dockerhub registry 

```
services:
  odoo:
    build: 
      context: .
```
      
  **from docker file ( probably this was the solution)     
      # Own folders    //-- docker-compose creates named volumes owned by root:root. Issue: https://github.com/docker/compose/issues/3270
RUN chown -R ${ODOO_USER}:${ODOO_USER} ${ODOO_DATA_DIR} ${ODOO_LOGS_DIR} /etc/odoo
RUN chmod u+x /entrypoint.sh**

**Comment by dev-flti** [comment]
![image](https://user-images.githubusercontent.com/64775806/116248538-3c9a8c00-a76c-11eb-950e-6d31fbf1decd.png)
 Unfortunately still having the same issue - even after i added to docker.file

`RUN chown -R ${ODOO_USER}:${ODOO_USER} ${ODOO_DATA_DIR} ${ODOO_LOGS_DIR} /etc/odoo
RUN chmod u+x /entrypoint.s`

**Dockerfile:**

`FROM python:3.8-slim-buster as base

SHELL ["/bin/bash", "-xo", "pipefail", "-c"]

USER root

# Library versions
ARG WKHTMLTOX_VERSION
ENV WKHTMLTOX_VERSION ${WKHTMLTOX_VERSION:-"0.12.5"}

ARG WKHTMLTOPDF_CHECKSUM
ENV WKHTMLTOPDF_CHECKSUM ${WKHTMLTOPDF_CHECKSUM:-"1140b0ab02aa6e17346af2f14ed0de807376de475ba90e1db3975f112fbd20bb"}

# Use noninteractive to get rid of apt-utils message
ENV DEBIAN_FRONTEND=noninteractive

# Install odoo deps
RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
    curl \
    && curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/${WKHTMLTOX_VERSION}/wkhtmltox_${WKHTMLTOX_VERSION}-1.stretch_amd64.deb \
    && echo "${WKHTMLTOPDF_CHECKSUM} wkhtmltox.deb" | sha256sum -c - \
    && apt-get install -y --no-install-recommends ./wkhtmltox.deb \
    && apt-get -qq install -y --no-install-recommends \
    ca-certificates \
    chromium \
    git-core \
    gnupg \
    htop \
    ffmpeg \
    fonts-liberation2 \
    fonts-noto-cjk \
    locales \
    lsb-release \
    node-less \
    npm \
    python3-num2words \
    python3-pip \
    python3-phonenumbers \
    python3-pyldap \
    python3-qrcode \
    python3-renderpm \
    python3-setuptools \
    python3-slugify \
    python3-vobject \
    python3-watchdog \
    python3-xlrd \
    python3-xlwt \
    nano \
    ssh \
    # Add sudo support for the non-root user & unzip for CI
    sudo \
    unzip \
    vim \
    zip \
    zlibc \
    xz-utils \
    && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > etc/apt/sources.list.d/pgdg.list \
    && GNUPGHOME="$(mktemp -d)" \
    && export GNUPGHOME \
    && repokey='B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8' \
    && gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "${repokey}" \
    && gpg --batch --armor --export "${repokey}" > /etc/apt/trusted.gpg.d/pgdg.gpg.asc \
    && gpgconf --kill all \
    && rm -rf "$GNUPGHOME" \
    && apt-get update  \
    && apt-get install --no-install-recommends -y postgresql-client \
    # && rm -f /etc/apt/sources.list.d/pgdg.list \
    && apt-get autopurge -yqq \
    && rm -Rf /var/lib/apt/lists/* wkhtmltox.deb /tmp/*

# Install rtlcss (on Debian buster)
RUN npm install -g rtlcss \
    && rm -Rf ~/.npm /tmp/*

FROM base as builder

# Install hard & soft build dependencies
RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
    apt-utils dialog \
    apt-transport-https \
    build-essential \
    libfreetype6-dev \
    libfribidi-dev \
    libghc-zlib-dev \
    libharfbuzz-dev \
    libjpeg-dev \
    libgeoip-dev \
    libmaxminddb-dev \
    liblcms2-dev \
    libldap2-dev \
    libopenjp2-7-dev \
    libssl-dev \
    libsasl2-dev \
    libtiff5-dev \
    libxml2-dev \
    libxslt1-dev \
    libpq-dev \
    libwebp-dev \
    lsb-release \
    tcl-dev \
    tk-dev \
    zlib1g-dev \
    && apt-get autopurge -yqq \
    && rm -Rf /var/lib/apt/lists/* /tmp/*

# Install Odoo source code and install it as a package inside the container with additional tools
ENV ODOO_VERSION ${ODOO_VERSION:-14.0}

RUN pip3 -qq install --prefix=/usr/local --no-cache-dir --upgrade --requirement https://raw.githubusercontent.com/odoo/odoo/${ODOO_VERSION}/requirements.txt \
    && pip3 -qq install --prefix=/usr/local --no-cache-dir --upgrade \
    'websocket-client~=0.56' \
    astor \
    black \
    pylint-odoo \
    flake8 \
    pydevd-odoo \
    psycogreen \
    python-magic \
    python-stdnum \
    pdfminer.six \
    click-odoo-contrib \
    git-aggregator \
    inotify \
    python-json-logger \
    wdb \
    redis \
    && apt-get autopurge -yqq \
    && rm -Rf /var/lib/apt/lists/* /tmp/*

RUN git clone --depth 100 -b ${ODOO_VERSION} https://github.com/odoo/odoo.git /opt/odoo \
    && pip3 install --editable /opt/odoo \
    && pip3 -qq install --prefix=/usr/local --no-cache-dir --upgrade \
    gevent==20.12.1 \
    greenlet==0.4.17 \
    Werkzeug==0.15.6 \
    # debugpy has python2 libraries which can't be compiled with python3
    debugpy \
    && rm -Rf /var/lib/apt/lists/* /tmp/*

FROM base as production

# PIP auto-install requirements.txt (change value to "1" to auto-install)
ENV PIP_AUTO_INSTALL=${PIP_AUTO_INSTALL:-"0"}

# Run tests for all the modules in the custom addons
ENV RUN_TESTS=${RUN_TESTS:-"0"}

# Upgrade all databases visible to this Odoo instance
ENV UPGRADE_ODOO=${UPGRADE_ODOO:-"0"}

    # Create app user
ENV ODOO_USER odoo
ENV ODOO_BASEPATH ${ODOO_BASEPATH:-/opt/odoo}
ARG APP_UID
ENV APP_UID ${APP_UID:-1000}

ARG APP_GID
ENV APP_GID ${APP_UID:-1000}

RUN addgroup --system --gid ${APP_GID} ${ODOO_USER} \
    && adduser --system --uid ${APP_UID} --ingroup ${ODOO_USER} --home ${ODOO_BASEPATH} --disabled-login --shell /sbin/nologin ${ODOO_USER} \
    && echo ${ODOO_USER} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${ODOO_USER}\
    && echo ${ODOO_USER} ALL=\(sudo\) NOPASSWD:ALL > /etc/sudoers.d/${ODOO_USER}\
    && chmod 0440 /etc/sudoers.d/${ODOO_USER} \
    && sudo usermod -aG sudo ${ODOO_USER} \
    && sudo usermod -aG root ${ODOO_USER}

# Odoo Configuration file variables and defaults
ARG ADMIN_PASSWORD
ARG DB_PORT_5432_TCP_ADDR
ARG DB_ENV_POSTGRES_USER
ARG DB_PORT_5432_TCP_PORT
ARG DB_ENV_POSTGRES_PASSWORD
ARG DB_TEMPLATE
ARG HTTP_INTERFACE
ARG HTTP_PORT
ARG DBFILTER
ARG DBNAME
ARG SERVER_WIDE_MODULES

ENV \
    ADMIN_PASSWORD=${ADMIN_PASSWORD:-my-weak-password} \
    ODOO_DATA_DIR=${ODOO_DATA_DIR:-/var/lib/odoo/data} \
    DB_PORT_5432_TCP_ADDR=${DB_PORT_5432_TCP_ADDR:-db} \
    DB_MAXCONN=${DB_MAXCONN:-64} \
    DB_ENV_POSTGRES_PASSWORD=${DB_ENV_POSTGRES_PASSWORD:-odoo} \
    DB_PORT_5432_TCP_PORT=${DB_PORT_5432_TCP_PORT:-5432} \
    DB_SSLMODE=${DB_SSLMODE:-prefer} \
    DB_TEMPLATE=${DB_TEMPLATE:-template1} \
    DB_ENV_POSTGRES_USER=${DB_ENV_POSTGRES_USER:-odoo} \
    DBFILTER=${DBFILTER:-.*} \
    DBNAME=${DBNAME:-False} \
    HTTP_INTERFACE=${HTTP_INTERFACE:-0.0.0.0} \
    HTTP_PORT=${HTTP_PORT:-8069} \
    LIMIT_REQUEST=${LIMIT_REQUEST:-8196} \
    LIMIT_MEMORY_HARD=${LIMIT_MEMORY_HARD:-2684354560} \
    LIMIT_MEMORY_SOFT=${LIMIT_MEMORY_SOFT:-2147483648} \
    LIMIT_TIME_CPU=${LIMIT_TIME_CPU:-60} \
    LIMIT_TIME_REAL=${LIMIT_TIME_REAL:-120} \
    LIMIT_TIME_REAL_CRON=${LIMIT_TIME_REAL_CRON:-0} \
    LIST_DB=${LIST_DB:-True} \
    LOG_DB=${LOG_DB:-False} \
    LOG_DB_LEVEL=${LOG_DB_LEVEL:-warning} \
    LOGFILE=${LOGFILE:-None} \
    LOG_HANDLER=${LOG_HANDLER:-:INFO} \
    LOG_LEVEL=${LOG_LEVEL:-info} \
    MAX_CRON_THREADS=${MAX_CRON_THREADS:-2} \
    PROXY_MODE=${PROXY_MODE:-False} \
    SERVER_WIDE_MODULES=${SERVER_WIDE_MODULES:-base,web} \
    SMTP_PASSWORD=${SMTP_PASSWORD:-False} \
    SMTP_PORT=${SMTP_PORT:-25} \
    SMTP_SERVER=${SMTP_SERVER:-localhost} \
    SMTP_SSL=${SMTP_SSL:-False} \
    SMTP_USER=${SMTP_USER:-False} \
    TEST_ENABLE=${TEST_ENABLE:-False} \
    UNACCENT=${UNACCENT:-False} \
    WITHOUT_DEMO=${WITHOUT_DEMO:-False} \
    WORKERS=${WORKERS:-0}

# camptocamp variables (to be used on cloud deployments)
# Sessions in Redis
ARG ODOO_SESSION_REDIS
ARG ODOO_SESSION_REDIS_HOST
ARG ODOO_SESSION_REDIS_PASSWORD
ARG ODOO_SESSION_REDIS_PREFIX
# JSON logging
ARG ODOO_LOGGING_JSON
# Attachments in the Object Storage S3
ARG AWS_HOST
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_BUCKETNAME
# Metrics (Statsd/Prometheus for Grafana)
ARG ODOO_STATSD
ARG STATSD_CUSTOMER
ARG STATSD_ENVIRONMENT
ARG STATSD_HOST
ARG STATSD_PORT
# Automatic Configuration Startup checks
ARG ODOO_CLOUD_PLATFORM_UNSAFE

ENV \
    ODOO_SESSION_REDIS=${ODOO_SESSION_REDIS:-0} \
    ODOO_SESSION_REDIS_HOST=${ODOO_SESSION_REDIS_HOST} \
    ODOO_SESSION_REDIS_PASSWORD=${ODOO_SESSION_REDIS_PASSWORD} \
    ODOO_SESSION_REDIS_PREFIX=${ODOO_SESSION_REDIS_PREFIX} \
    ODOO_LOGGING_JSON=${ODOO_LOGGING_JSON:-0} \
    AWS_HOST=${AWS_HOST} \
    AWS_REGION=${AWS_REGION} \
    AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
    AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
    AWS_BUCKETNAME=${AWS_BUCKETNAME} \
    ODOO_STATSD=${ODOO_STATSD} \
    STATSD_CUSTOMER=${STATSD_CUSTOMER} \
    STATSD_ENVIRONMENT=${STATSD_ENVIRONMENT} \
    STATSD_HOST=${STATSD_HOST} \
    STATSD_PORT=${STATSD_PORT}

# Define all needed directories
ENV ODOO_RC ${ODOO_RC:-/etc/odoo/odoo.conf}
ENV ODOO_DATA_DIR ${ODOO_DATA_DIR:-/var/lib/odoo/data}
ENV ODOO_LOGS_DIR ${ODOO_LOGS_DIR:-/var/lib/odoo/logs}
ENV ODOO_EXTRA_ADDONS ${ODOO_EXTRA_ADDONS:-/mnt/extra-addons}
ENV ODOO_ADDONS_BASEPATH ${ODOO_BASEPATH}/addons
ENV ODOO_CMD ${ODOO_BASEPATH}/odoo-bin

RUN mkdir -p ${ODOO_DATA_DIR} ${ODOO_LOGS_DIR} ${ODOO_EXTRA_ADDONS} /etc/odoo/

VOLUME ["${ODOO_DATA_DIR}", "${ODOO_LOGS_DIR}", "${ODOO_EXTRA_ADDONS}"]

ARG EXTRA_ADDONS_PATHS
ENV EXTRA_ADDONS_PATHS ${EXTRA_ADDONS_PATHS}

ARG EXTRA_MODULES
ENV EXTRA_MODULES ${EXTRA_MODULES}

COPY --chown=${ODOO_USER}:${ODOO_USER} --from=builder /usr/local /usr/local
COPY --chown=${ODOO_USER}:${ODOO_USER} --from=builder /opt/odoo ${ODOO_BASEPATH}

# Copy from build env
COPY --chown=${ODOO_USER}:${ODOO_USER} ./resources/entrypoint.sh /
COPY --chown=${ODOO_USER}:${ODOO_USER} ./resources/getaddons.py /

# This is needed to fully build with modules and python requirements
# Copy custom modules from the custom folder, if any.
ARG HOST_CUSTOM_ADDONS
ENV HOST_CUSTOM_ADDONS ${HOST_CUSTOM_ADDONS:-./custom}
COPY --chown=${ODOO_USER}:${ODOO_USER} ${HOST_CUSTOM_ADDONS} ${ODOO_EXTRA_ADDONS}

# Own folders    //-- docker-compose creates named volumes owned by root:root. Issue: https://github.com/docker/compose/issues/3270
RUN chown -R ${ODOO_USER}:${ODOO_USER} ${ODOO_DATA_DIR} ${ODOO_LOGS_DIR} /etc/odoo /var/lib/odoo
RUN chmod u+x /entrypoint.sh


EXPOSE 8069 8071 8072 

# Docker healthcheck command
HEALTHCHECK CMD curl --fail http://127.0.0.1:8069/web_editor/static/src/xml/ace.xml || exit 1

ENTRYPOINT ["/entrypoint.sh"]
USER ${ODOO_USER}
CMD ["sh", "-c", "${ODOO_CMD}"]
#CMD ["/opt/odoo/odoo-bin"]
`

Is there any solution?

**Comment by Garibaldy** [comment]
> ![image](https://user-images.githubusercontent.com/64775806/116248538-3c9a8c00-a76c-11eb-950e-6d31fbf1decd.png)
> Unfortunately still having the same issue - even after i added to docker.file
> 
> `RUN chown -R ${ODOO_USER}:${ODOO_USER} ${ODOO_DATA_DIR} ${ODOO_LOGS_DIR} /etc/odoo RUN chmod u+x /entrypoint.s`
> 
> **Dockerfile:**
> 
> [Dockerfil.txt](https://github.com/iterativo-git/dockerdoo/files/6384851/Dockerfil.txt)
> 
> Is there any solution?

Did you try to rebuild the image ??? as i explainned before

**Comment by evaldez89** [comment]
I was having the same issue. 

This is what's happening:
![image](https://user-images.githubusercontent.com/12959163/119239847-e1b14600-bb19-11eb-942f-1558e4c09983.png)

After a `sudo chown odoo:odoo -R odoo` it was fixed for me:

![image](https://user-images.githubusercontent.com/12959163/119239859-f7bf0680-bb19-11eb-8c63-cd5dbb67b07d.png)

I'm still investigating how to fix it to avoid having to do it manually.

**Comment by gustavovalverde** [comment]
Fixed by: https://github.com/iterativo-git/dockerdoo/pull/137/commits/9a312d0b12609e875055f4d9750c6ea897c098eb
