### ISSUE TITLE
Error al copiar el contendio de custom a /mnt/extra-addons

### ISSUE THREAD

**Issue by FranMercedesG** [iterativo-git/dockerdoo#140]
Saludos,

No se esta copiando el contenido del directorio custom a /mnt/extra-addons al momento de crear una instancia.

- git clone -b 14.0 https://github.com/iterativo-git/dockerdoo.git
- cd dockerdoo/custom
- git clone (todos los addons de la imagen)

![image](https://user-images.githubusercontent.com/46732695/139700095-72c09f98-96c4-48d8-b24a-ae46e34252cf.png)
![image](https://user-images.githubusercontent.com/46732695/139700497-22de61a8-77c1-47e1-aee3-f8d10d49d76c.png)

**Comment by evaldez89** [comment]
> Saludos,
> 
> No se esta copiando el contenido del directorio custom a /mnt/extra-addons al momento de crear una instancia.
> 
> * git clone -b 14.0 https://github.com/iterativo-git/dockerdoo.git
> * cd dockerdoo/custom
> * git clone (todos los addons de la imagen)
> 
> ![image](https://user-images.githubusercontent.com/46732695/139700095-72c09f98-96c4-48d8-b24a-ae46e34252cf.png) ![image](https://user-images.githubusercontent.com/46732695/139700497-22de61a8-77c1-47e1-aee3-f8d10d49d76c.png)

@FranMercedesG debes ejecutarlo para standalone dev

```bash
docker-compose -f docker-compose.yml -f dev-standalone.yml up -d
```

Esto monta `./custom` como un volumen para que estén disponibles los extra addons en el contenedor:

![image](https://user-images.githubusercontent.com/12959163/142975021-4db6021e-3ef2-42b7-b903-dbef20f2752a.png)
