### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by jeremi** [iterativo-git/dockerdoo#144]
Great project, but the absence of a license makes it hard to reuse it.
Do you plan to publish it under an open-source license?
Would you consider Apache or MIT?

**Comment by gustavovalverde** [comment]
Thanks for raising this concern. I'll fix this ASAP.

**Comment by gustavovalverde** [comment]
Fixed by https://github.com/iterativo-git/dockerdoo/commit/f1203a2c97607cd19ef3b9ad7c43f6c93504c669

**Comment by jeremi** [comment]
Thank you!
