### ISSUE TITLE
Module auto discover no funciona con diferentes profundides de directorios 

### ISSUE THREAD

**Issue by akevinieron** [iterativo-git/dockerdoo#15]
Si coloco en el directorio de extra addons un directorio con multiples modulos y tambien un modulo directamente en el root, el autodiscover obvia uno de los 2.

**Comment by gustavovalverde** [comment]
El "best practice" es que todos los módulos se encuentren al mismo nivel. Si clonas un repositorio el mismo tiene módulos dentro con 1 solo nivel; si tiene el módulo en el root esto es mala práctica y por igual causa en estas instalaciones comportamientos erróneos.
