### ISSUE TITLE
Exponer el puerto 8069

### ISSUE THREAD

**Issue by Garibaldy** [iterativo-git/dockerdoo#20]
No se puede **acceder a odoo** a traves del localhost URL **localhost:8069**

he notado que al correr 

**docker-compose up odoo**   #Standalone 

**no expone el puerto 8069 correctamente** para interactuar  odoo a traves de la web

he notado que usualmente en el **dockerfile** se pone de esta manera en otras imagenes

**EXPOSE 8069/tcp**

**Comment by gustavovalverde** [comment]
El `EXPOSE` más bien sirve como documentación; en la práctica realmente no publica esos puertos.

Pero lo que mencionas ya fue corregido aquí: https://github.com/iterativo-git/dockerdoo/commit/0c38f6696225c6d07abe8debf993b31a3f700bbc#diff-3254677a7917c6c01f55212f86c57fbfR26
