### ISSUE TITLE
Optimizar el tamaño de las imagenes

### ISSUE THREAD

**Issue by Garibaldy** [iterativo-git/dockerdoo#36]
he notado que las imagenes oficial de odoo en su docker file utiliza 

- **debian stretch**, cuyo tamaño **comprimido es muchisimo menor (unos 300MB menos)** que la que se esta usando python:3.7
- y para la base de datos  usar una version de postgress con alpine, **algunos 200MB comprimidos menos ,** ej postgress:10-alpine

en la practica ,la imagenes oficiales tienen muchisimo menos tamaño a la hora de uso 
si hago un docker images me ecuentro con algo como esto :

- dockerdoo:11 -> 3.02GB
- odoo:11 -> 1.1GB

- postgress:11 -> 293MB
- postgress:10-alpine -> 71.8MB

la imagen de dockerdoo se podria reducir mucho mas con alpine, aunque en mi opinion lo ideal es seguir los **"lineamientos"** de la imagen oficial  al menos en esa parte.

**Nota:** Si hay alguna razon por la que esto se deba mantener como está favor explicar

**Comment by akevinieron** [comment]
Gracias por tus comentarios @Garibaldy. 

Pasar a Postgres Alpine es válido. Es un cambio previsto que nunca se realizó. En cambio, manejar todas las dependencias de Odoo y de los módulos con Alpine es un poco tedioso, no solo lograr que corra sino también evitar sacrificar performance.

En cuanto al Debian, esa imagen viene con Python 3.5 y por eso preferimos utilizar Python:3.7 como base (requerimiento de módulos que tenemos en producción y mejoras en general).

**Comment by Garibaldy** [comment]
Me estaba refiriendo  a *debian:stretch-slim* para la imagen de Odoo y uno mismo instalar las dependencias de python como se hace en las imagenes [*oficiales*](url)  de odoo

**Comment by akevinieron** [comment]
Actualmente se está usando Debian, solo que la imagen de Python 3.7, pero no deja de ser Debian. Entendemos que la imagen oficial de Python sobre Debian viene mejor preparada para producción que la instalación corriente que podamos hacer con apt.

**Comment by Garibaldy** [comment]
Estuve verificando algunas maneras de optimizar el dockerfile  y me encontre con esto , aunque al final el resultado fue el mismo (al menos en tamaño de la imagen) 

- https://www.fromlatest.io/#/

Revisando el dockerfile note que hay muchas librerias que se instalan **"por si acaso se instalan los modulos de OCA"** por el momento no se me ocurre como pero debe haber algunas manera de optimizar las dependencias de la imagen y reducir su tamaño hasta ahora con el nuevo cambio tiene unos 300 MB menos
