### ISSUE TITLE
Se debe eliminar el container de Odoo al agregar un directorio de modulos nuevo

### ISSUE THREAD

**Issue by akevinieron** [iterativo-git/dockerdoo#37]

**Comment by Garibaldy** [comment]
Podrias describir un ejemplo puntual del caso ?

**Comment by gustavovalverde** [comment]
Ping @akevinieron. 

What?

**Comment by akevinieron** [comment]
oh, facil!

Luego de tener mi instancia corriendo agrego un directorio de módulos al directorio custom.

**Comment by Garibaldy** [comment]
Lo que suelo hacer en ese caso en particular es que si tengo directorios para addons lo agrego al archivo de configuracion odoo.conf , dentro de un directorio ya existente 

algo como : 

addons_path = /mnt/extra-addons, 
 /mnt/extra-addons/oca_web, /mnt/extra-addons/oca_crm
