### ISSUE TITLE
Variable de entorno innecesaria ODOO_FRM

### ISSUE THREAD

**Issue by akevinieron** [iterativo-git/dockerdoo#4]
La variable de entorno ODOO_FRM no se usa para nada!!

**Comment by gustavovalverde** [comment]
Se usa en el docker-compose para definir dónde está el framework de Odoo. 

Ahora mismo tenemos una instalación **bridged** a nuestro Host, pero la idea es también agregar una *standalone*, que para lograr tener esta es necesario poder ubicar dónde está el framework de Odoo para instalar desde el src.

**Comment by akevinieron** [comment]
Eso del "standalone" se resuelve haciendo el clonado de odoo en el Dockerfile. Literalmente con una linea!

**Comment by gustavovalverde** [comment]
Y hay forma de ponerle un IF? Porque no siempre irá.

**Comment by akevinieron** [comment]
Si pero no es necesario, porque cuando haces un volumen, basicamente estas sobreescribiendo el directorio completo. Entonces donde estara el odoo clonado es el mismo directorio al que le hacemos el volumen, quiere decir que cuando tengamos nuestro volumen con el codigo de odoo, va a tomar el nuestro y no el que existe en la imagen.
