### ISSUE TITLE
Le falta una instruccion CMD al Dockerfile

### ISSUE THREAD

**Issue by akevinieron** [iterativo-git/dockerdoo#5]
A pesar de que en el compose se utiliza el comando a ejecutar. Lo correcto es que la propia imagen tenga su comando por defecto para poder utilzarla facilmente como los usuarios de Docker estamos acostumbrados

**Comment by gustavovalverde** [comment]
¿Cuál sería la diferencia de incluirla en el Dockerfile si la ejecución debe ser a través del docker-compose?

**Comment by akevinieron** [comment]
Porque el compose NO puede ser una dependencia de tu imagen. Esa imagen debe funcionar correctamente y de la mejor manera por si misma. Si no tiene el CMD, estaras obligando al usuario que haga un run a siempre tener que indicar la ejecucion del servicio de odoo, pero eso es algo que no deberia ser.

**Comment by gustavovalverde** [comment]
Ok, entiendo perfectamente; y tienes razón. 

Pero ¿Cómo vamos a resolver el tema de que todas las ejecuciones utilizan la misma imagen? La idea no es tener una imagen para cada comando:
- docker-compose up odoo --> producción
- docker-compose up dev --> debugging
- docker-compose up tests --> unit test
- docker-compose up shell --> CLI de Odoo

Cada uno de esos ejecuta un CMD diferente en el compose ¿Cómo logramos lo mismo cambiando el CMD a la imagen?

**Comment by akevinieron** [comment]
Recuerda que el CMD es el comando por defecto, cuando corres el contenedor y le pasas parametros estos se corren en lugar del CMD de la imagen. Por ej, la imagen de nginx tiene el comando "nginx" en el CMD, pero al momento de crear el contenedor haces "docker run nginx bash", en lugar de correr el CMD que tiene la imagen, correra el bash que le pasaste al momento de ejecutar el run. Del mismo modo, cada comando del compose tendra su propio comando que invalidara el que viene por defecto en la imagen!

**Comment by gustavovalverde** [comment]
Dígase, que vamos a dejar las que tiene el docker-compose. Solo aque adicional le pondremos la default a la imagen
